f1 = open("../python_class/Example1.txt", "w")
f1.write("Just a small town boy\n\nSuccessful!")
f1.close()
f1 = open("../python_class/Example1.txt", "r")
lines = f1.readline()
print(lines)
f1.close()
f4 = open("../python_class/Example4.txt", "w")
f4.write(lines)
f4.close()

f2 = open("../python_class/Example2.txt", "w")
f2.write("Born and raised in south Detroit\n\nSuccessful!")
f2.close()
f2 = open("../python_class/Example2.txt", "r")
lines = f2.readline()
print(lines)
f2.close()
f4 = open("../python_class/Example4.txt", "a")
f4.write(lines)
f4.close()

f3 = open("../python_class/Example3.txt", "w")
f3.write("Took the midnight train going anywhere\n\nSuccessful!")
f3.close()
f3 = open("../python_class/Example3.txt", "r")
lines = f3.readline()
print(lines)
f3.close()
f4 = open("../python_class/Example4.txt", "a")
f4.write(lines)
f4.close()

f4 = open("../python_class/Example4.txt", "r")
lines = f4.read()
print(lines)